config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  # get 'reports/report'
  get 'reports/report_by_category'
  get 'reports/report_by_dates'
  get 'main/index'
  resources :operations
  resources :categories do
    resources :operations
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :operations, dependent: :destroy
    validates :name, presence: true, uniqueness: true
    validates :description, presence: true
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :category
  validates :amount, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :description, :odate, presence: true
  validates :category_id, presence: true
  validates :otype, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: %i[ show edit update destroy ]
   before_action :get_categories
  # GET /operations or /operations.json
  def index
    @operations = Operation.all
  end

  # GET /operations/1 or /operations/1.json
  def show
  end

  # GET /operations/new
  def new
    @operation = Operation.new
  end

  # GET /operations/1/edit
  def edit
  end

  # POST /operations or /operations.json
  def create
    @operation = Operation.new(operation_params)

    respond_to do |format|
      if @operation.save
        format.html { redirect_to operation_url(@operation), notice: "Operation was successfully created." }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1 or /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to operation_url(@operation), notice: "Operation was successfully updated." }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1 or /operations/1.json
  def destroy
    @operation.destroy

    respond_to do |format|
      format.html { redirect_to operations_url, notice: "Operation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def get_categories
      @categories = Category.all.order(:name)
    end
    
    def set_operation
      @operation = Operation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def operation_params
      params.require(:operation).permit(:amount, :odate, :description, :otype, :category_id)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    puts params
    if params[:btn_date]
      redirect_to({ 
        action: "report_by_dates", 
        category_id: params[:category],
        otype: params[:otype],
        start_date: params[:start_date], 
        end_date: params[:end_date]
      })
    elsif params[:btn_cat]
      redirect_to({
        action: "report_by_category",
        category_id: params[:category],
        otype: params[:otype],
        start_date: params[:start_date], 
        end_date: params[:end_date]
        
    })
    end
  end

  def report_by_category

    @data = params
    @category = Category.find(params[:category_id])
    @operation = Operation.where("category_id": params[:category_id])
    @total = @operation.sum(:amount)

    @dataArr = @operation.map{|el| [el.amount.to_i, el.description ]}
    @amount = @dataArr.map {|sum| sum[0]}
    @description = @dataArr.map {|d| d[1]}
  end

  def report_by_dates
    @data = params
    @category = Category.find(params[:category_id])
    @operationList = Operation.where("category_id": @category.id)
    @dataArr = @operationList.map{|el| [el.amount.to_i, el.odate.strftime("%d/%m/%Y")]}

   @dates = @dataArr.map {|d| d[1]}.sort
   @rates = @dataArr.map {|d| d[0]}
  
  end

  def operation_params
      params.require(:operation).permit(:amount, :odate, :description, :otype, :operation_id, :category_name, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">

  <h2 class='mb-3'> <%= category.name %> </h2>
<p>
    <strong>Опис категорії:</strong>
    <%= category.description %>
  </p>

  <% if category.operations.present? %>
<div id="categories" class="table-responsive">  
    <table class = "table table-striped table-hover table-bordered align-middle table-sm caption-top">
    <caption>Список операцій</caption>
   <thead>
      <tr class="table-info">
         <th scope="col">Опис операції</th>
         <th scope="col">Сума</th>
         <th scope="col">Дата</th>
         <th scope="col" class="text-center">Управління операціями </th>
      </tr>
   </thead>
   
   <tbody   
      <% category.operations.each do |operation| %> 
         <tr>
            <td><%= operation.description %></td>
            <td><%= operation.amount %></td>
            <td><%= operation.odate %></td>
            <td class="text-center"><%= link_to "View operation", operation, class: "btn btn-outline-info" %> </td>     
         </tr> 
      <% end %>        
   </tbody>
  </table>
</div>
<% else %>
<div class="notFound">
<h3>Операцій за категорією <%= category.name %> не знайдено :( </h3>
</div>
<% end %>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div class="mt-3">
    <%= form.submit "Зберегти", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Редагувати категорію</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<section id='categories-section' class="section">
<p style="color: green"><%= notice %></p>

<h2 class='mb-3'>Категорії витрат\доходів </h2>
<% if @categories.present? %>
<div id="categories" class="table-responsive">  
    <table class = "table table-bordered table-striped table-hover table-bordered align-middle">
   <thead>
      <tr class="table-warning">
         <th scope="col">Назва</th>
         <th scope="col">Опис</th>
         <th scope="col" colspan="3" class="text-center">Управління категоріями </th>
      </tr>
   </thead>
   
   <tbody   
      <% @categories.each do |category| %>   
         <tr>
            <td><%= category.name %></td>
            <td><%= category.description %></td>

            <td class="text-center"><%= link_to "Відкрити категорію", category, class: "btn btn-outline-info" %> </td>
            <td class="text-center"><%= link_to "Редагувати", edit_category_path(category), class: "btn btn-outline-success btn-sm" %> </td>
            <td class="text-center"> <%= button_to "Видалити", category, method: :delete, class: 'btn btn-danger btn-sm', data: {"turbo-confirm": "Ви впевнені що хочете видалити #{category.name}?"}  %></td>
         </tr> 
      <% end %>        
   </tbody> 
   <tfoot>
  <tr class="table-warning">
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
         </tr> 
  </tfoot>
  </table>
</div>
<% else %>
<h3>Ой, категорій ще не створено :( </h3>
<% end %>
<%= link_to "New category", new_category_path, class: "btn btn-primary" %>
</section>

app/views/categories/new.html.erb
<div class="category-new mb-5  d-inline-block section">
<h2 class="pb-5">Нова категорія</h2>

  <div class="operation-form">
      <%= render "form", category: @category %>
      <br>
    <div>
      <%= link_to "Назад до категорій", categories_path, class: "btn btn-secondary btn-sm" %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  
  <%= link_to "Назад до категорій", categories_path, class: "btn btn-secondary"  %>  

  
</div>

app/views/layouts/_footer.html.erb
<footer id="footer" class="fixed-bottom mb-3">

<div class="container-fluid ">
   <div class="row align-items-center">
      <div class="col">
       <a class="navbar-brand" href="/">
        <svg xmlns="http://www.w3.org/2000/svg" width="33" height="26" fill="#800000" class="bi bi-piggy-bank-fill" viewBox="0 0 16 16">
       <path d="M7.964 1.527c-2.977 0-5.571 1.704-6.32 4.125h-.55A1 1 0 0 0 .11 6.824l.254 1.46a1.5 1.5 0 0 0 1.478 1.243h.263c.3.513.688.978 1.145 1.382l-.729 2.477a.5.5 0 0 0 .48.641h2a.5.5 0 0 0 .471-.332l.482-1.351c.635.173 1.31.267 2.011.267.707 0 1.388-.095 2.028-.272l.543 1.372a.5.5 0 0 0 .465.316h2a.5.5 0 0 0 .478-.645l-.761-2.506C13.81 9.895 14.5 8.559 14.5 7.069c0-.145-.007-.29-.02-.431.261-.11.508-.266.705-.444.315.306.815.306.815-.417 0 .223-.5.223-.461-.026a.95.95 0 0 0 .09-.255.7.7 0 0 0-.202-.645.58.58 0 0 0-.707-.098.735.735 0 0 0-.375.562c-.024.243.082.48.32.654a2.112 2.112 0 0 1-.259.153c-.534-2.664-3.284-4.595-6.442-4.595Zm7.173 3.876a.565.565 0 0 1-.098.21.704.704 0 0 1-.044-.025c-.146-.09-.157-.175-.152-.223a.236.236 0 0 1 .117-.173c.049-.027.08-.021.113.012a.202.202 0 0 1 .064.199Zm-8.999-.65a.5.5 0 1 1-.276-.96A7.613 7.613 0 0 1 7.964 3.5c.763 0 1.497.11 2.18.315a.5.5 0 1 1-.287.958A6.602 6.602 0 0 0 7.964 4.5c-.64 0-1.255.09-1.826.254ZM5 6.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z"/>
       </svg>
          <span class="text-warning">Budget</span>App
       </a>
      </div>
    
      <div class="col">
        <p class = "copyright">Copyright &copy 2023 Nataliia Kotelnytska. Всі права захищені.</p>
      </div>
   </div>
</div>
</footer>

app/views/layouts/_navbar.html.erb
<header class=" bg ">
 <nav class="navbar navbar-expand-lg navbar-light border-bottom border-warning"  >
  <div class="container-fluid text-center">
    <a class="navbar-brand " href="/">
     <svg xmlns="http://www.w3.org/2000/svg" width="33" height="26" fill="#800000" class="bi bi-piggy-bank-fill" viewBox="0 0 16 16">
       <path d="M7.964 1.527c-2.977 0-5.571 1.704-6.32 4.125h-.55A1 1 0 0 0 .11 6.824l.254 1.46a1.5 1.5 0 0 0 1.478 1.243h.263c.3.513.688.978 1.145 1.382l-.729 2.477a.5.5 0 0 0 .48.641h2a.5.5 0 0 0 .471-.332l.482-1.351c.635.173 1.31.267 2.011.267.707 0 1.388-.095 2.028-.272l.543 1.372a.5.5 0 0 0 .465.316h2a.5.5 0 0 0 .478-.645l-.761-2.506C13.81 9.895 14.5 8.559 14.5 7.069c0-.145-.007-.29-.02-.431.261-.11.508-.266.705-.444.315.306.815.306.815-.417 0 .223-.5.223-.461-.026a.95.95 0 0 0 .09-.255.7.7 0 0 0-.202-.645.58.58 0 0 0-.707-.098.735.735 0 0 0-.375.562c-.024.243.082.48.32.654a2.112 2.112 0 0 1-.259.153c-.534-2.664-3.284-4.595-6.442-4.595Zm7.173 3.876a.565.565 0 0 1-.098.21.704.704 0 0 1-.044-.025c-.146-.09-.157-.175-.152-.223a.236.236 0 0 1 .117-.173c.049-.027.08-.021.113.012a.202.202 0 0 1 .064.199Zm-8.999-.65a.5.5 0 1 1-.276-.96A7.613 7.613 0 0 1 7.964 3.5c.763 0 1.497.11 2.18.315a.5.5 0 1 1-.287.958A6.602 6.602 0 0 0 7.964 4.5c-.64 0-1.255.09-1.826.254ZM5 6.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z"/>
     </svg>
      <span class="text-warning ">Budget</span>App
    </a>
    
      <ul class="navbar-nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
        <li class="nav-item">
          <a class="nav-link icon-link icon-link-hover"  aria-current="page" href="/">
            <svg xmlns="http://www.w3.org/2000/svg" class="bi d-block mx-auto mb-1" width="24" height="24" fill="#800000" viewBox="0 0 16 16">
              <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146ZM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5Z"/>
            </svg>
          Home
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle"  href="/categories" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <svg xmlns="http://www.w3.org/2000/svg" fill="#800000" class="bi bi-journal-text d-block mx-auto mb-1" width="24" height="24" viewBox="0 0 16 16">
              <path d="M5 10.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5zm0-2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0-2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0-2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
              <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z"/>
              <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z"/>
            </svg>
          Категорії
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/categories">Категорії</a></li>
            <li><a class="dropdown-item" href="/categories/new">Додати категорію</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle"  href="/categories" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           <svg xmlns="http://www.w3.org/2000/svg" fill="#800000" class="bi bi-cash-coin d-block mx-auto mb-1" width="24" height="24" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z"/>
            <path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z"/>
            <path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z"/>
            <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z"/>
           </svg>
          Операції
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/operations">Операції</a></li>
            <li><a class="dropdown-item" href="/operations/new">Додати операцію</a></li>
          </ul>
          </li>
        <li class="nav-item">
          <a class="nav-link" href="/reports/index">
           <svg xmlns="http://www.w3.org/2000/svg" fill="#800000" class="bi d-block mx-auto mb-1" width="24" height="24" viewBox="0 0 16 16">
             <path d="M6.5 0A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3Zm3 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3Z"/>
             <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1A2.5 2.5 0 0 1 9.5 5h-3A2.5 2.5 0 0 1 4 2.5v-1ZM10 8a1 1 0 1 1 2 0v5a1 1 0 1 1-2 0V8Zm-6 4a1 1 0 1 1 2 0v1a1 1 0 1 1-2 0v-1Zm4-3a1 1 0 0 1 1 1v3a1 1 0 1 1-2 0v-3a1 1 0 0 1 1-1Z"/>
            </svg>
          Звіти</a>
        </li>
      </ul>
   
  </div>
 </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container-fluid bgr">
     <%= render 'layouts/navbar' %>
    <%= yield %>
     <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/operations/edit.html.erb
<h1>Editing operation</h1>

<%= render "form", operation: @operation %>

<br>

<div>
  <%= link_to "Show this operation", @operation %> |
  <%= link_to "Back to operations", operations_path %>
</div>

app/views/operations/index.html.erb
<section class='operations-section section'>
<p style="color: green"><%= notice %></p>

<h2>Список операцій</h2>
<% if @operations.present? %>
<div id="operations" class="table-responsive">

    <table class = "table table-bordered table-striped table-hover table-bordered align-middle">
   <thead>
      <tr class="table-warning">
         <th scope="col">Опис</th>
         <th scope="col">Сума</th>
         <th scope="col">Дата</th>
         <th scope="col" class="text-center">Категорія</th>
         <th scope="col">Управління</th>
      </tr>
   </thead>
   
   <tbody   
      <% @operations.each do |operation| %>  
        <tr>
            <td><%= operation.description %> </td>
            <td><%= operation.amount %></td>
            <td><%= operation.odate.to_date %></td>
            <td class="text-center"> <%=link_to operation.category.name, operation.category%></td>
            <td><%= link_to "View operation", operation, class: "btn btn-outline-info" %> </td>
         </tr>      
      <% end %>        
   </tbody> 
   <tfoot>
  <tr class="table-warning">
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
         </tr> 
  </tfoot>
  </table>

</div>
<% else %>
<div class="notFound">
<h3>Операцій не знайдено :( </h3>
</div>
<% end %>
   
<%= link_to "Нова операція", new_operation_path(@operation), class: "btn btn-success" %>
</section>

app/views/operations/new.html.erb
<h1>New operation</h1>

<%= render "form", operation: @operation %>

<br>

<div>
  <%= link_to "Back to operations", operations_path %>
</div>

app/views/operations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @operation %>

<div class="mt-5">
   <%= link_to "Редагувати", edit_operation_path( @operation), class: "btn btn-success btn-sm mb-3" %> 
  
  <%= button_to "Видалити", [@category, @operation], method: :delete, class: 'btn btn-danger btn-sm mb-3'%>
  <%= link_to "Back to operations", operations_path, class: "btn btn-secondary" %>
</div>

app/views/reports/report_by_category.html.erb
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<section class="report-by-category-section section">
  <h2 class="text-center">Звіт по категорії <span class="text-warning"><%= @category.name %></span></h2>

  <div class="d-flex justify-content-between">
  <div id="report-by-category_table" class="table-responsive w-50">  
    <table class = "table table-striped table-hover table-bordered align-middle table-sm caption-top">
    <caption>Список операцій</caption>
   <thead>
      <tr class="table-info table-warning">
         <th scope="col">Опис операції</th>
         <th scope="col">Сума</th>
         <th scope="col">Дата</th>
      </tr>
   </thead>
   
   <tbody   
      <% @category.operations.each do |operation| %> 
         <tr>
            <td><%= operation.description %></td>
            <td><%= operation.amount %></td>
            <td><%= operation.odate.to_date %></td>
         </tr> 
      <% end %>        
   </tbody>
   <tfoot class="table-info">
      <tr>
         <td colspan="3"> Всього: <%= @total%></td>
      </tr> 
    
  </tfoot> 
  </table>
</div>

  <div class="chart-container" style="position: relative; height:50vh; width:50vh">
  <canvas id="myChart"></canvas>
  </div>

<script>
  const ctx = document.getElementById('myChart');

const data = {
  labels: <%=raw @description %> ,
  datasets: [{
    label: 'My First Dataset',
    data: <%= @amount %>,
    backgroundColor: [
      'rgb(	255,215,0)',
      'rgb(54, 162, 235)',
      'rgb(0, 204, 0)',
      'rgb(255, 153, 204)',
      'rgb(153, 153, 255)',
      'rgb(210,105,30)'
    ],
    hoverOffset: 4
  }]
};
 const config = {
  type: 'pie',
  data: data,
};

  new Chart(ctx, config);
</script>

 
</div>
<%= link_to "Назад до генератора звітів", reports_index_path, class: "btn btn-secondary mt" %>
</div>

app/views/reports/report_by_dates.html.erb
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<section class="report-by-category-section section">
<h2 class="text-center">Звіт по <span class="text-warning">датам</span></h2>

  <div>
    <%= link_to "Назад до генератора звітів", reports_index_path, class: "btn btn-secondary mt" %>
  </div>
  <div>
    <canvas id="myChart"></canvas>
  </div>

<script>
  const ctx = document.getElementById('myChart');

  new Chart(ctx, {
    type: 'line',
    data: {
      labels: <%= raw @dates %>,
      datasets: [{
        label: 'Сума',
        data: <%= @rates %>,
         fill: false,
    borderColor: 'rgb(75, 192, 192)',
    tension: 0.1
      }]
    },
    options: {
      scales: {
        y: {
          beginAtZero: true
        }
      }
    }
  });
</script>

</section>

 